apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  KAFKA_SERVER: kafka:9092
  KAFKA_TOPIC: tiksup-user-data
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  PG_HOST: postgres
  PG_PORT: "5432"
  PG_NAME: tiksup
  SPARK_HOST: spark-master
  SPARK_PORT: "7077"
  GATEWAY_PORT: "3000"
  WORKER_PORT: "8081"
  CLIENT_PORT: "3001"
  GATEWAY_URL: http://gateway:3000
  PROCESSOR_URL: http://processor:8000
  WORKER_URL: http://worker:8081

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SECRET_KEY: ZmFkZTc1MzEtYzI1Ni00OWY2LTk2NmItNjU5NWMzYzAzMTI4Cg==
  PG_USER: dXNlcg==  # Base64 encoding for "user"
  PG_PASSWORD: YWRtaW4=  # Base64 encoding for "admin"
  MONGO_USER: dXNlcg==
  MONGO_PASSWORD: YWRtaW4=
  MONGO_DB: dGlrc3Vw
  MONGO_COLLECTION: bW92aWVz
